language: haskell

branches:
    only:
        -   master

notifications:
  webhooks:
    urls:
        -   https://webhooks.gitter.im/e/e80ceb37bab1d58c4128
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
